apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-mrfp
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0035-tenant/tkrw-pr712-0075-0035-app/devfile-sample-mrfp@sha256:992417e198f2342ed81a183f8877c27a19636cb44b31986f2bec77d3cf0a1418
        name: my-nodejs
        resources: {}
status: {}
